### ISSUE TITLE
Redirection to OAuth login page not working

### ISSUE THREAD

**Issue by ruedigerkupper** [DJaeger/files_external_dropbox#9]
When pressing "grant access", nothing happens. I should be redirected to the OAuth login web page, but I don't.

**Comment by DJaeger** [comment]
Have you setup OAuth for Dropbox like described in the README?
https://github.com/DJaeger/files_external_dropbox#configuring-oauth2

**Comment by powerpaul17** [comment]
I did, and I still get an error in the console: `TypeError: result.data is undefined`. Stepping into in reveals that `oauth2.php` does not return anything. Also the dialog is not shown because it is not checked if `result.data.message` is defined.

**Comment by ruedigerkupper** [comment]
Yes, I did.

**Comment by powerpaul17** [comment]
I just realized that I had the app installed in a "custom_apps" folder instead of the "apps" folder (which was the standard configuration for docker. Symlinking the dropbox app into "apps" solved the problem.

**Comment by ruedigerkupper** [comment]
It's still not working for me. I use the Nextcloud snap.

**Comment by DJaeger** [comment]
Please update the app and make sure you have correctly setup OAuth like in app description

**Comment by ruedigerkupper** [comment]
Sorry, this issue is still unchanged. Redirection to the OAuth page does *not* work, although config is as described in https://github.com/DJaeger/files_external_dropbox#configuring-oauth2.
Please reopen this issue.

I have tested in Chromium, Chrome and Firefox: Neither browser opens the OAuth page when I press "Grant Access". What information can I provide to help debugging the problem?

**Comment by kuvic** [comment]
It's exactly the same here, with Nextcloud snap. App install from App store, enabled, nothing happens when pressing Grant Access but this message:
`TypeError: result.data is undefined`

**Comment by DJaeger** [comment]
Please verify the following and give me response:
- App is installed in directory "apps"
- Redirect URIs are both in Dropbox App
- Redirect URIs are available in your setup (mayby you have some index.php in your URLs?
- Are you redirected? Wich pages you walk through
- Have you used Client Id and Client Secret? NOT userid/mail and password
- Do you have errors in NC Log

**Comment by DJaeger** [comment]
There's a Typo in the OAuth process...
For allowing user mounts, you need to add
```https://mycloud.example.com/settings/user/externalstorages```
and not
```https://mycloud.example.com/settings/admin/externalstorages```

**Comment by DJaeger** [comment]
And you are required to use http*s*!

**Comment by kuvic** [comment]
Thanks so much for the quick reply!
> 
> 
> Please verify the following and give me response:
> 
>     * App is installed in directory "apps"
I have to investigate more. NC is installed via snap and app from NC app store, I have to log in to the server and check out (Should I look somewhere specific?)
> 
>     * Redirect URIs are both in Dropbox App
See image in link. I think yes.
> 
>     * Redirect URIs are available in your setup (mayby you have some index.php in your URLs?
Indeed there is index.php and I have added it to Redirect URI.
> 
>     * Are you redirected? Wich pages you walk through
Nothing happens when pressing GRANT ACCESS BUTTON, only the error I mention in previous post.
> 
>     * Have you used Client Id and Client Secret? NOT userid/mail and password
Yes.
> 
>     * Do you have errors in NC Log
No.

https://paste.pics/8QQEW

**Comment by DJaeger** [comment]
As @powerpaul17 told in https://github.com/DJaeger/files_external_dropbox/issues/9#issuecomment-567162377
the app could be in "custom_apps".
So would be nice if you would investigate some more :-)

Please also check if there appear some errors in your browsers console (F12).

**Comment by kuvic** [comment]
Browser error from console is when I press the "Grant Access: button:
`TypeError: result.data is undefined oauth2.js:87:7
    <anonymous> oauth2.js:87
    jQuery 4
        c
        fireWith
        k
        t
`

App is installed in /var/snap/nextcloud/20498/nextcloud/extra-apps
I hope this helps! As I mentioned before I am running a snap installation. Running find -iname *apps* does not reveal any other *apps* directory.

**Comment by bbolokofsky** [comment]
Same problem with grant access button not doing anything when pressed.  Mine was also installed in custom apps so I did a Symlink to apps, but my browser is reporting "HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
GET - https://docs.kstech.com/apps/files_external_dropbox/js/dropbox.js?v=83bb97e8-0".  We are using docker.

**Comment by gonzonia** [comment]
I also am using docker. App was installed in custom_apps. Made symlink to apps. Getting the following error in the browser when loading the externalstorages page. https://my.nextcloudinstall.com/apps/files_external_dropbox/js/dropbox.js?v=4fac9f4c-14 net::ERR_ABORTED 403

It's trying to access this relative URL. 
 src="/apps/files_external/js/../../files_external_dropbox/js/dropbox.js?v=4fac9f4c-14"

Permissions on the directory are the same as on files_external. Any ideas where to ook?

**Comment by DJaeger** [comment]
Would you please try again with:
https://github.com/DJaeger/files_external_dropbox/releases/download/v1.4.1/files_external_dropbox.tar.gz

I would update to app store, but its currently down

**Comment by gonzonia** [comment]
Is there a recommended method for updating? Can I just extract the files over the old ones? I'm a bit new to docker and not exactly sure the best way to make this work successfully .

**Comment by DJaeger** [comment]
You could, but you should delete the app folder and extract the new one

**Comment by gonzonia** [comment]
Okay. I did that. 
When loading the External Storages page I now get this error- 
`externalstorages#:1 Refused to execute script from 'https://my.nextcloud.site/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`


Then when I try to "Grant Access" I get this one-
`oauth2.js?v=750feffa-14:87 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.success (oauth2.js?v=750feffa-14:87)
    at c (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at k (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)`

**Comment by DJaeger** [comment]
Looks like we are one step closer
I will investigate some more, but I currently have not a snap or docker test environment.

**Comment by DJaeger** [comment]
Both external storage addons were disabled before you extracted and enabled afterwards?

**Comment by gonzonia** [comment]
No, but there was no activity. I extracted and when I connected again it prompted about updating the app, ran it's checks and finished. I'll try the following. 
Remove app. Reinstall from store. Disable external storage and dropbox app. Replace directory with new files. Re-enable.

**Comment by gonzonia** [comment]
Same issue. (also getting an error about a deprecated call to .tooltip (destroy) that was there the whole time too, just didn't think it relevant.  Sorry if it is and I should have mentioned

**Comment by DJaeger** [comment]
Seems to me as its an upstream issue as oauth2.php is part of files_external.
But I will investigate some more.

**Comment by DJaeger** [comment]
Fixed with new version 1.4.2 recently published to Github and app store

**Comment by TauPan** [comment]
I'm still getting the same error with Nextcloud 17.0.8.1 (upgraded today) and 1.4.2.
```js
oauth2.js?v=12e45388-0:87 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.success (oauth2.js?v=12e45388-0:87)
    at c (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at k (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
```

Also the tooltip errors and `refused to execute script` mentioned by others.
